export const SET_INTIAL_COORDS = "  SET_INTIAL_COORDS";
export const CHANGE_DIRECTION = "CHANGE_DIRECTION";
export const SET_PREVIOUS_ROBOT = "SET_PREVIOUS_ROBOT";
export const SET_NEW_COORDS = "SET_NEW_COORDS";
